export const iPhones = [
  "iPhone XS",
  "iPhone XS Max",
  "iPhone XR",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPhone SE(2020)",
  "iPhone 12 mini",
  "iPhone 16",
  "iPhone 16 Pro Max",
  "iPhone 12",
  "iPhone 12 Pro",
  "iPhone 12 Pro Max",
  "iPhone 13 mini",
  "iPhone 13",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPhone SE(2022)",
  "iPhone 16 Plus",
  "iPhone 14",
  "iPhone 14 Plus",
  "iPhone 14 Pro",
  "iPhone 14 Pro Max",
  "iPhone 15",
  "iPhone 15 Plus",
  "iPhone 15 Pro",
  "iPhone 15 Pro Max",
  "iPhone 16 Pro",
];

export const samsungPhones = [
  "Samsung Galaxy S23",
  "Samsung Galaxy S23+",
  "Samsung Galaxy S23",
  "Samsung Galaxy S22",
  "Samsung Galaxy S22+",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S21",
  "Samsung Galaxy S21+",
  "Samsung Galaxy Z Fold5 5G",
  "Samsung Galaxy S24 Ultra",
  "Samsung Galaxy S21 Ultra",
  "Samsung Galaxy S20",
  "Samsung Galaxy S20+",
  "Samsung Galaxy S2 Ultra",
  "Samsung Galaxy S23",
  "Samsung Galaxy Note 20",
  "Samsung Galaxy Note 20 Ultra",
  "Samsung Galaxy Fold",
  "Samsung Galaxy S24",
  "Samsung Galaxy Z Flip 6",
  "Samsung Galaxy Fold 2",
  "Samsung Galaxy Fold 3",
  "Samsung Galaxy Fold 4",
  "Samsung Galaxy Flip 1",
  "Samsung Galaxy Flip 3",
  "Samsung Galaxy Flip 4",
  "Samsung Galaxy S20 Hybrid Dual SIM",
  "Samsung Galaxy Z Flip5 5G",
  "Samsung Galaxy S24 Plus",
  "Samsung Galaxy XCover 7",
  "Samsung Galaxy S25",
  "Samsung Galaxy S25+",
  "Samsung Galaxy S25 Ultra",
  "Samsung Galaxy S25 Edge",
  "Samsung Galaxy S25 Slim",
  "Samsung Galaxy S24 FE",
  "Samsung Galaxy A54 5G",
  "Samsung Galaxy S23FE",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy A55 5G",
  "Samsung Galaxy Z Fold6",
  "Samsung Galaxy Z Fold4",
  "Samsung Galaxy Flip4",
  "Samsung Galaxy Z Fold3",
  "Samsung Galaxy Flip3",
  "Samsung Galaxy Z Fold2",
  "Samsung Galaxy Z Flip 5G",
  "Samsung Galaxy Z Flip",
];

export const googlePixel = [
  "Google Pixel 2",
  "Google Pixel 2 XL",
  "Google Pixel 3",
  "Google Pixel 3 XL",
  "Google Pixel 3a",
  "Google Pixel 3a XL",
  "Google Pixel Fold",
  "Google Pixel 9",
  "Google Pixel 7a",
  "Google Pixel 4",
  "Google Pixel 4 XL",
  "Google Pixel 4a 5G",
  "Google Pixel 5",
  "Google Pixel 5a",
  "Google Pixel 6",
  "Google Pixel 9 Pro",
  "Google Pixel 9 Pro Fold",
  "Google Pixel 6 Pro",
  "Google Pixel 6a",
  "Google Pixel 7",
  "Google Pixel 7 Pro",
  "Google Pixel 8",
  "Google Pixel 8 Pro",
  "Google Pixel 9 Pro XL",
  "Google Pixel 8a",
];

export const huaweiPhones = [
  "Huawei P40",
  "Huawei P40 Pro",
  "Huawei Pura 70 Pro",
  "Huawei P50 Pro",
  "Huawei Mate 40 Pro",
  "Huawei Mate Xs 2",
  "Huawei Mate X2",
];

export const oppoPhones = [
  "Oppo Find X3 Pro",
  "Oppo Reno 5A",
  "Oppo Find X5",
  "Oppo Find X5 Pro",
  "Oppo Find X3",
  "Oppo Reno 6 Pro 5G",
  "Oppo Find X3 Pro",
  "Oppo Find X5",
  "Oppo Find X5 Pro",
];

export const oppoPhones2 = [
  "Oppo A55s 5G",
  "Oppo Find X8",
  "Oppo Reno6 Pro 5G",
  "Oppo Find N2 Flip",
  "Oppo Find N3",
  "Oppo Find N3 Flip",
  "Oppo Reno 9A",
];

export const sonyPhones = [
  "Sony Xperia 10 III Lite",
  "Sony Xperia 1 IV",
  "Sony Xperia 10 IV",
  "Sony Xperia 10 VI",
  "Sony Xperia 5 IV",
  "Sony Xperia 1 V",
  "Sony Xperia 1 VI",
  "Sony Xperia 10 V",
  "Sony Xperia Ace III",
  "Sony Xperia 5 V",
];

export const xiaomiPhones = [
  "Xiaomi 12T Pro",
  "Xiaomi 13",
  "Xiaomi 14",
  "Xiaomi 13T",
  "Xiaomi 15",
  "Redmi Note 14 Pro+",
  "Xiaomi 13 Lite",
  "Xiaomi 13 Pro",
  "Xiaomi 14 Pro",
  "Xiaomi 15 Ultra",
  "Xiaomi 14T Pro",
  "Redmi Note 14 Pro",
];
export const xiaomiPhones2 = [
  "Xiaomi 13T Pro",
  "Xiaomi Blackshark 3",
  "Xiaomi 15 Pro",
  "Xiaomi Redmi Note 13 Pro+",
  "Redmi Note 13 Pro 5G",
  "Xiaomi Redmi Note 11 Pro 5G (Japan only)",
];

export const motorolaPhones = [
  "Motorola Razr 2019",
  "Motorola Razr 5G",
  "Motorola Razr 2022",
  "Motorola Razr 40",
  "Motorola Edge 40",
  "Motorola Razr+",
  "Motorola Edge 2022",
  "Motorola Edge 2023",
  "Motorola Edge+ (2023)",
  "Motorola Edge 40 Pro",
  "Motorola Edge 40 Neo",
  "Motorola Edge 50 Pro",
];

export const motorolaPhones2 = [
  "Motorola Edge 50 Ultra",
  "Motorola Edge 50 Fusion",
  "Motorola Moto G Power 5G (2024)",
  "Motorola G52J 5G",
  "Motorola G52J 5G Ⅱ",
  "Motorola Razr 40 Ultra",
  "Motorola G53J 5G",
  "Moto G54 5G",
  "Motorola G84",
  "Motorola G34",
  "Motorola Moto G53",
  "Motorola Moto G54",
  "Motorola Razr 2019",
  "Motorola Razr 5G",
  "Motorola Moto G Stylus 5G",
];

export const honorPhones = [
  "HONOR Magic4 Pro",
  "HONOR Magic7 Pro",
  "HONOR Magic V3",
  "HONOR Magic7 Lite",
  "HONOR Magic5 Pro",
  "HONOR Magic Vs",
  "HONOR 90",
  "HONOR Magic6 Pro",
  "HONOR Magic V2",
  "HONOR 200",
];

export const otherPhones = [
  "Motorola Razr 2019",
  "Motorola Razr 5G",
  "Gemini PDA",
  "Rakuten Mini",
  "Rakuten BigS",
  "OnePlus 12",
];

export const otherPhones2 = [
  "Rakuten Big",
  "Rakuten Hand",
  "Rakuten Hand 5G",
  "Surface Pro X",
  "Surface Duo",
  "Fairphone 4",
  "Sharp Aquos Sense 6s",
  "Sharp Aquos Wish",
  "DOOGEE V30",
  "Nuu Mobile X5",
  "Fairphone 5",
];

export const phonesTableData = [
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone XR",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone XS",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone XS Max",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 11",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 11 Pro",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 11 Pro Max",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone SE(2020)",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 12 Mini",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 12",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 12 Pro",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 12 Pro Max",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 13 mini",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 13",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 13 Pro",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 13 Pro Max",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone SE(2022)",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 14",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 14 Plus",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 14 Pro",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 14 Pro Max",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 15",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 15 Plus",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 15 Pro",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPhone 15 Pro Max",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPad Pro (2018 and onwards)",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPad Air",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Apple",
    phoneModel: "iPad",
    NoOfeSIMs: "20",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 3",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 3a",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 4",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 4a",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 5",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 6",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 6a",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 6 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 7",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 7 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 8",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel 8 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Google",
    phoneModel: "Pixel Fold",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Huawei",
    phoneModel: "P40",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Huawei",
    phoneModel: "P40 Pro (not including the P40 Pro +)",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Huawei",
    phoneModel: "Mate 40 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "Razr 2019",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "Razr 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "Razr 40",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "Razr 40 Ultra",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "Razr+",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "Edge+",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "Edge 40",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "Edge 40 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "G52J 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "G52J 5G  Ⅱ",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Motorola",
    phoneModel: "G53J 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Flip",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Flip 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Flip3 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Flip4",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Flip5 5G",
    NoOfeSIMs: "+5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Fold",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Fold2 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Fold3 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Fold4",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Z Fold5 5G",
    NoOfeSIMs: "+5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S20",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S20+ 5G",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S20 Ultra",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S20 Ultra 5G",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S21",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S21+ 5G",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S21 Ultra 5G",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S22",
    NoOfeSIMs: "+5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S22+",
    NoOfeSIMs: "+5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S22 Ultra",
    NoOfeSIMs: "+5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Note 20 Ultra 5G",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy Note 20",
    NoOfeSIMs: "5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S23",
    NoOfeSIMs: "+5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S23+",
    NoOfeSIMs: "+5",
  },
  {
    Manufacturer: "Samsung",
    phoneModel: "Galaxy S23 Ultra",
    NoOfeSIMs: "+5",
  },
  {
    Manufacturer: "Rakuten Mobile",
    phoneModel: "Rakuten Mini",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Rakuten Mobile",
    phoneModel: "Big-S",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Rakuten Mobile",
    phoneModel: "Big",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Rakuten Mobile",
    phoneModel: "Hand",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Rakuten Mobile",
    phoneModel: "Hand 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Oppo",
    phoneModel: "Find N2 Flip",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Oppo",
    phoneModel: "Find X3 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Oppo",
    phoneModel: "Reno 5 A",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Oppo",
    phoneModel: "Find X5",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Oppo",
    phoneModel: "Find X5 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Oppo",
    phoneModel: "A55s 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Oppo",
    phoneModel: "Reno 6 Pro 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sony",
    phoneModel: "Xperia 10 III Lite",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sony",
    phoneModel: "Xperia 10 IV",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sony",
    phoneModel: "Xperia 10V",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sony",
    phoneModel: "Xperia 1 IV",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sony",
    phoneModel: "Xperia 5 IV",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sony",
    phoneModel: "Xperia 1 V",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sony",
    phoneModel: "Sony Xperia Ace III",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Honor",
    phoneModel: "Magic 4 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Honor",
    phoneModel: "Magic 5 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Honor",
    phoneModel: "90",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Xiaomi",
    phoneModel: "12T Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Xiaomi",
    phoneModel: "13",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Xiaomi",
    phoneModel: "13 Lite",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Xiaomi",
    phoneModel: "13 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Xiaomi",
    phoneModel: "13T Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos Sense6s",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos sense 7",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos sense 7plus",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos Wish",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos wish 2 SHG08",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos wish3",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos Sense4 lite",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos zero 6",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Simple Sumaho6",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos R7",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos R8",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Sharp",
    phoneModel: "Aquos R8 Pro",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "DOOGEE",
    phoneModel: "V30",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "OnePlus",
    phoneModel: "11",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "HAMMER",
    phoneModel: "Blade 3",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "HAMMER",
    phoneModel: "Explorer PRO",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "HAMMER",
    phoneModel: "Blade 5G",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Nokia",
    phoneModel: "XR21",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Nokia",
    phoneModel: "X30",
    NoOfeSIMs: "1",
  },
  {
    Manufacturer: "Nokia",
    phoneModel: "G60 5G",
    NoOfeSIMs: "1",
  },
];
